import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dot Streak — Terms & Conditions",
  description: "Terms and Conditions for the Dot Streak mobile app.",
};

export default function DotStreakTermsPage() {
  return (
    <article className="prose-none">
      <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">
        Dot Streak — Terms &amp; Conditions
      </h1>
      <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">
        Last updated: July 2026
      </p>

      <p className="mt-8 text-sm leading-6 text-slate-600 dark:text-slate-400">
        These Terms &amp; Conditions (&ldquo;Terms&rdquo;) govern your use of
        the Dot Streak mobile app (&ldquo;the app&rdquo;), developed by
        Praootech (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By downloading,
        installing, or using the app, you agree to these Terms.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        1. The service
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        Dot Streak helps you track daily habits and streaks, and sends you
        reminder notifications. Some features, such as short AI-generated
        nudge messages, rely on a backend service and require an internet
        connection.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        2. Accounts
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        You sign in using your Google account. You are responsible for
        keeping that account secure. We are not responsible for losses
        resulting from unauthorized access to your Google account.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        3. Acceptable use
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        You agree not to misuse the app, including attempting to disrupt its
        backend services, reverse-engineer it beyond what applicable law
        permits, or use it for any unlawful purpose.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        4. AI-generated content
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        Nudge messages shown in reminder notifications may be generated by an
        AI model based on the names of your pending streaks. These messages
        are provided for motivational purposes only, are not guaranteed to
        be accurate or available at all times, and should not be relied upon
        for any purpose beyond a friendly reminder.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        5. Disclaimer of warranties
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        The app is provided &ldquo;as is&rdquo; without warranties of any
        kind, express or implied. We do not guarantee the app will be
        uninterrupted, error-free, or that your data will never be lost;
        we recommend using the backup feature if you want a copy of your
        data preserved.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        6. Limitation of liability
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        To the maximum extent permitted by law, Praootech will not be liable
        for any indirect, incidental, or consequential damages arising from
        your use of the app.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        7. Changes to the app or these Terms
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        We may update the app or these Terms from time to time. Continuing to
        use the app after changes take effect constitutes acceptance of the
        updated Terms.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        8. Termination
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        You may stop using the app at any time and request deletion of your
        account as described on our{" "}
        <a
          href="/dotstreak/delete-account"
          className="text-blue-600 underline hover:no-underline dark:text-blue-400"
        >
          Account &amp; Data Deletion
        </a>{" "}
        page. We may suspend or terminate access for users who violate these
        Terms.
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        9. Governing law
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        [Governing law and jurisdiction to be confirmed by Praootech.]
      </p>

      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">
        10. Contact us
      </h2>
      <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">
        Questions about these Terms? Email us at{" "}
        <a
          href="mailto:praootech@gmail.com"
          className="text-blue-600 underline hover:no-underline dark:text-blue-400"
        >
          praootech@gmail.com
        </a>
        .
      </p>
    </article>
  );
}
